name: Test Setup With Retry

on:
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest
    env:
      BUILD: ./selfdrive/test/docker_build.sh
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # 👈 This MUST run before the local action

      - name: Run setup-with-retry
        uses: ./.github/workflows/setup-with-retry
        with:
          sleep_time: 0
          docker_hub_pat: ""
